CREATE TABLE customer
(
    customer_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    boarding_pass_id UNKNOWN__SEM4.JAVAAIRPORT.PERSISTENCE.ENTITY.BOARDINGPASSENTITY,
    country          VARCHAR(255),
    CONSTRAINT pk_customer PRIMARY KEY (customer_id)
);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_BOARDINGPASS FOREIGN KEY (boarding_pass_id) REFERENCES boarding_pass (customer_id, baggage_id, flight_id);

CREATE TABLE boarding_pass
(
    customer_id BIGINT NOT NULL,
    baggage_id  BIGINT NOT NULL,
    flight_id   BIGINT NOT NULL,
    CONSTRAINT pk_boardingpass PRIMARY KEY (customer_id, baggage_id, flight_id)
);

ALTER TABLE boarding_pass
    ADD CONSTRAINT FK_BOARDINGPASS_ON_BAGGAGE FOREIGN KEY (baggage_id) REFERENCES baggage (baggage_id);

ALTER TABLE boarding_pass
    ADD CONSTRAINT FK_BOARDINGPASS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

ALTER TABLE boarding_pass
    ADD CONSTRAINT FK_BOARDINGPASS_ON_FLIGHT FOREIGN KEY (flight_id) REFERENCES flight (flight_id);

CREATE TABLE flight
(
    flight_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    panel_number   VARCHAR(255),
    travel_company VARCHAR(255),
    CONSTRAINT pk_flight PRIMARY KEY (flight_id)
);
CREATE TABLE baggage
(
    baggage_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code             VARCHAR(255),
    weight           DOUBLE PRECISION,
    boarding_pass_id UNKNOWN__SEM4.JAVAAIRPORT.PERSISTENCE.ENTITY.BOARDINGPASSENTITY,
    status           VARCHAR(255),
    remark           VARCHAR(255),
    CONSTRAINT pk_baggage PRIMARY KEY (baggage_id)
);

ALTER TABLE baggage
    ADD CONSTRAINT FK_BAGGAGE_ON_BOARDINGPASS FOREIGN KEY (boarding_pass_id) REFERENCES boarding_pass (customer_id, baggage_id, flight_id);
CREATE TABLE employee
(
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    job_title   VARCHAR(255),
    CONSTRAINT pk_employee PRIMARY KEY (employee_id)
);
CREATE TABLE action
(
    type        VARCHAR(255),
    employee_id BIGINT NOT NULL,
    baggage_id  BIGINT NOT NULL,
    CONSTRAINT pk_action PRIMARY KEY (employee_id, baggage_id)
);

ALTER TABLE action
    ADD CONSTRAINT FK_ACTION_ON_BAGGAGE FOREIGN KEY (baggage_id) REFERENCES baggage (baggage_id);

ALTER TABLE action
    ADD CONSTRAINT FK_ACTION_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (employee_id);